version: '3.9'
services:
  metabase-mysql:
    image: metabase/metabase-enterprise:v1.43.4
    container_name: metabase-mysql
    hostname: metabase-mysql
    volumes: 
    - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment: 
      MB_DB_DBNAME: "metabase"
      MB_DB_PORT: "3306"
      MB_DB_USER: "metabase"
      MB_DB_PASS: "mysecretpassword"
      MB_DB_HOST: "mysql"
      MB_DB_TYPE: "mysql"
    networks: 
      - metanet1-mysql
  mysql-app-db:
    image: mysql:8.0.29
    container_name: mysql
    hostname: mysql
    ports: 
      - 3306:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=mysecretpassword"
      - "MYSQL_USER=metabase"
      - "MYSQL_PASSWORD=mysecretpassword"
      - "MYSQL_DATABASE=metabase"
    volumes:
      - $PWD/mysql-data:/var/lib/mysql
    command: ['--default-authentication-plugin=mysql_native_password', '--mysqlx=0']
    networks: 
      - metanet1-mysql
networks: 
  metanet1-mysql:
    driver: bridge